# Generated by Django 3.0.2 on 2020-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('registrado_em', models.DateTimeField(verbose_name='data do registro')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(verbose_name='data da reserva')),
                ('data_evento', models.DateTimeField(verbose_name='data do evento')),
                ('pessoas', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=type, to='reservas.Cliente')),
            ],
        ),
    ]
