# Generated by Django 3.0.2 on 2020-01-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
